name: flutter_onboarding_screen_adaptive
description: "Flutter package that provides a customizable onboarding experience for new users. It includes a series of pages with navigation controls and animations, designed to introduce users to the app's features in a user-friendly manner."
homepage: https://github.com/badiniibrahim/flutter_onboarding_screen_adaptive
repository: https://github.com/badiniibrahim/flutter_onboarding_screen_adaptive

version: 2.0.3

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  get_cli: ^1.8.1
  animate_do: ^3.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 300
        - asset: assets/fonts/Gilroy-Heavy.ttf
          weight: 100
        - asset: assets/fonts/Gilroy-Light.ttf
          weight: 600
        - asset: assets/fonts/Gilroy-Medium.ttf
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 200
